//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication5
{
    using System;
    using System.Collections.Generic;
    
    public partial class transaction
    {
        [System.ComponentModel.DataAnnotations.Key]
        public int transId { get; set; }
        public int customerId { get; set; }
        public string receiverName { get; set; }
        public string accountNo { get; set; }
        public int amount { get; set; }
    
        public virtual customer customer { get; set; }
    }
}
